# image will be published to ghcr.io/<user>/<name>
name: zenix
# description will be included in the image's metadata
description: Zenix OS image WIP

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
    - type: files
      files:
          - source: system
            destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

    - type: rpm-ostree
      repos:
          - https://download.docker.com/linux/fedora/docker-ce.repo
          - https://github.com/terrapkg/subatomic-repos/raw/main/terra.repo
      install:
          - terra-release
          - starship
          - fish
          - fd-find
          - adw-gtk3-theme
          - ripgrep
          - bat
          - eza
          - fzf
          - vim
          - docker
          - distrobox
          - cryfs
          - baobab
      remove:
          # example: removing firefox (in favor of the flatpak)
          # "firefox" is the main package, "firefox-langpacks" is a dependency
          - firefox
          - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

    - type: default-flatpaks
      notify: false # Send notification after install/uninstall is finished (true/false)
      system:
          # If no repo information is specified, Flathub will be used by default
          # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
          # repo-name: flathub
          # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
          install:
              - org.mozilla.firefox
              - org.gnome.Loupe
              - org.gnome.Papers
              - io.gitlab.adhami3310.Impression
              - com.mattjakeman.ExtensionManager
              - org.gnome.Showtime
              - com.github.tchx84.Flatseal
              # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
          # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
          # only normal flatpak applications are (like Floorp Lightning web browser in this example).
          # Installing different branches of the same Flatpak is not supported.
          remove:
              - org.gnome.eog
              - org.gnome.Evince
              - org.fedoraproject.MediaWriter
              - org.gnome.Extensions
              - org.gnome.Totem

    - type: signing # this sets up the proper policy & signing files for signed images to work fully
